services:
  app:
    build:
      context: ./docker/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./src:/var/www
      - ./src/public:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_CONFIG: client_host=host.docker.internal
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  worker:
    build:
      context: ./docker/php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./src:/var/www
    depends_on:
      - app
      - redis
    environment:
      QUEUE_CONNECTION: redis
    command: >
      php /var/www/artisan queue:work
      redis        
      --queue=default
      --sleep=3
      --tries=3
      -vv

volumes:
  pgdata:
  redisdata:
